# pull stack images
- name: Pull hubserver image
  docker_image:
    name: "{{ hubserver_image }}"
    state: present
    force: "{{ pull_images_always }}"
    timeout: 3600

- name: Pull openresty image
  docker_image:
    name: "{{ openresty_server }}"
    state: present
    force: "{{ pull_images_always }}"

- name: Pull notifications-server image
  docker_image:
    name: "{{ notifications_server_image }}"
    state: present
    force: "{{ pull_images_always }}"

- name: Pull logspout image
  docker_image:
    name: "{{ logspout_image }}"
    state: present
    force: "{{ pull_images_always }}"

- name: Pull docker-stats image
  docker_image:
    name: "{{ docker_stats_image }}"
    state: present
    force: "{{ pull_images_always }}"

# pull jupyter notebook images
- name: Pull jupyterlab image
  docker_image:
    name: "{{ notebook_lab_image }}"
    state: present
    force: "{{ pull_images_always }}"

- name: Pull scipy-notebook image
  docker_image:
    name: "{{ notebook_scipy_image }}"
    state: present
    force: "{{ pull_images_always }}"

# pull model and job images
- name: Pull job-py3 image
  docker_image:
    name: "{{ job_py3_image }}"
    state: present
    force: "{{ pull_images_always }}"

- name: Pull model-py3 image
  docker_image:
    name: "{{ model_py3_image }}"
    state: present
    force: "{{ pull_images_always }}"

# pull data source images
- name: Pull MongoDB image
  docker_image:
    name: "{{ mongo_image }}"
    state: present

- name: Pull Cassandra image
  docker_image:
    name: "{{ cassandra_image }}"
    state: present

- name: Pull MySQL image
  docker_image:
    name: "{{ mysql_image }}"
    state: present

- name: Pull PostgreSQL image
  docker_image:
    name: "{{ postgres_image }}"
    state: present
