# Ansible requires python2, which is not installed by default on Ubuntu Xenial
- name: Install python for Ansible
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  changed_when: False
- setup: # aka gather_facts

- name: Install apt-get packages
  apt: name={{ item }} update-cache=yes state=present cache_valid_time=3600
  with_items:
    - python-dev
    - python-setuptools

- name: Install pip
  easy_install:
      name=pip

- name: Upgrade pip
  command: pip install --upgrade pip

- name: Add docker apt-get repo
  apt_repository:
      repo='deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main'
      state=present

- name: Import the Docker repository key
  apt_key:
      url=https://apt.dockerproject.org/gpg
      state=present
      id=2C52609D

- name: Install Docker
  apt:
      name=docker-engine
      update_cache=yes

- name: Install  docker-py
  pip: name=docker-py version=1.10.6 state=present

- name: Install docker-compose
  pip: name=docker-compose version=1.9.0 state=present

- name: Create docker group
  group:
      name=docker
      state=present

- name: Add current user to docker group
  user:
    name={{ lookup('env', 'USER') }}
    group=docker
    state=present
  notify:
    - restart docker

- name: Increase virtual memory to avoid memory constraints when run on smaller instance
  command: sysctl -w vm.max_map_count=262144

- name: Read docker.service file
  shell: cat /lib/systemd/system/docker.service
  register: docker_service_content

- name: Enable docker to listen on tcp by modifying the docker.service file (only if it was not modified)
  when: docker_service_content.stdout.find('tcp://0.0.0.0:2375') == -1
  replace:
    dest: /lib/systemd/system/docker.service
    replace: ' fd:// -H tcp://0.0.0.0:2375'
    regexp: '(\s+)fd:\/\/'

- name: Flush changes
  command: systemctl daemon-reload

- name: Restart docker service
  command: systemctl restart docker
